mtc <- mtcars
mtc[, c('am', 'cyl', 'vs', 'gear', 'carb')] <- lapply(mtcars[,c('am', 'cyl', 'vs', 'gear', 'carb')], factor)
fit1 <- lm(mpg ~ am, mtc)
fit2 <- lm(mpg ~ am + qsec, mtc)
fit3 <- lm(mpg ~ am*qsec, mtc)
fit4 <- lm(mpg ~ am*qsec + wt, mtc)
fit5 <- lm(mpg ~ am*qsec + hp, mtc)
fit6 <- lm(mpg ~ am*qsec + cyl, mtc)
fit7 <- lm(mpg ~ am*qsec + disp, mtc)
fit8 <- lm(mpg ~ am*qsec + vs, mtc)
fit9 <- lm(mpg ~ am*qsec + carb, mtc)
fit10 <- lm(mpg ~ am*qsec + drat, mtc)
fit11 <- lm(mpg ~ am*qsec + gear, mtc)
print(anova(fit1, fit2, fit3, fit4))
print(anova(fit1, fit2, fit3, fit5))
print(anova(fit1, fit2, fit3, fit6))
print(anova(fit1, fit2, fit3, fit7))
print(anova(fit1, fit2, fit3, fit8))
print(anova(fit1, fit2, fit3, fit9))
print(anova(fit1, fit2, fit3, fit10))
print(anova(fit1, fit2, fit3, fit11))

