mtc <- mtcars
mtc[, c('am', 'cyl', 'vs', 'gear', 'carb')] <- lapply(mtcars[,c('am', 'cyl', 'vs', 'gear', 'carb')], factor)
fit1 <- lm(mpg ~ am, mtc)
fit2 <- lm(mpg ~ am + wt, mtc)
#fit3 <- update(fit2, mpg ~ am*wt)
#fit4 <- update(fit3, mpg ~ am*wt + qsec)
#fit5 <- update(fit4, mpg ~ am*wt + qsec + hp*qsec)
#fit6 <- update(fit5, mpg ~ am*wt + qsec + hp*qsec + hp*am)
fit3 <- lm(mpg ~ am*wt, mtc)
fit4 <- lm(mpg ~ am*wt + qsec, mtc)
fit5 <- lm(mpg ~ am*wt + qsec + hp*qsec, mtc)
fit6 <- lm(mpg ~ am*wt + qsec + hp*qsec + hp*am, mtc)
print(anova(fit1, fit2, fit3, fit4, fit5, fit6))
#print(summary(fit4)$adj.r.squared)
print(summary(fit4))
#print(summary(fit5)$adj.r.squared)
print(summary(fit5))
print(confint.lm(fit5))